# Generated by Django 3.0.2 on 2020-05-04 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0005_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tag',
            field=models.ManyToManyField(blank=True, default='start', related_name='orders', to='works.Tag'),
        ),
    ]
